openapi: 3.0.0
info:
  version: 1.0.0
  title: Express Gateway API
  description: Provides centralized access endpoints for spa Vue application to access all other available services.
tags:
  - name: Security services
    description: Provides secure login and user credential translation to jwt token
  
  - name: Warehouse management services
    description: Provides secured access to warehouse mgmt. service using JWT token

  - name: Material management services
    description: Provides secured access to material mgmt. service using JWT token
paths:
  /login:
    post:
      tags:
        - Security services
      description: Authenticate user and return roles and jwt token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Security artifact successfuly generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /login/verify:
    get:
      tags:
        - Security services
      description: Verify token of the authenticated user
      parameters:
        - $ref: "#/components/parameters/ibm-sec-token"
      
      responses:
        "200":
          description: Security artifact successfuly verified
          
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /gateway/wmj/journal:
    post:
      tags:
        - Warehouse management services
      description: Verify token of the authenticated user
      parameters:
        - $ref: "#/components/parameters/ibm-sec-token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenericRequest"
        description: Generic request to be passed on to target service
        required: false
      responses:
        "200":
          description: Security artifact successfuly verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              
  
    get:
      tags:
        - Warehouse management services
      description: Verify token of the authenticated user
      parameters:
        - $ref: "#/components/parameters/ibm-sec-token"
        - $ref: "#/components/parameters/generic-parameters"
      
      responses:
        "200":
          description: Security artifact successfuly verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /gateway/mms:
    post:
      tags:
        - Material management services
      description: Verify token of the authenticated user
      parameters:
        - $ref: "#/components/parameters/ibm-sec-token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenericRequest"
        description: Generic request to be passed on to target service
        required: false
      responses:
        "200":
          description: Security artifact successfuly verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              
  
    get:
      tags:
        - Material management services
      description: Verify token of the authenticated user
      parameters:
        - $ref: "#/components/parameters/ibm-sec-token"
        - $ref: "#/components/parameters/generic-parameters"
      
      responses:
        "200":
          description: Security artifact successfuly verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "401":
          description: Forbidden due wrong or missing privilegies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: Api endpoint not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "5XX":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  
  parameters:
    generic-parameters:
      name: generic-parameters
      in: query
      required: false
      description: Generic parameters
      schema:
        type: Object
    
    ibm-sec-token:
      name: ibm-sec-token
      in: header
      required: true
      description: JWT security token for mutual trust between apps
      schema:
        type: string

    
    
    id:
      name: id
      in: path
      required: true
      description: The id of the existing trusted document or entity of any type (document, participant, organization)
      schema:
        type: string
  
    pin:
      name: pin
      in: path
      required: true
      description:  Pin kterým se prokaze , ze Approver je opravnen zaznam schvalit, PIN vznikne automaticky pri odeslani ke schvaleni, zde jako parametr, ktery se porovna s PIN ulozenym v blockchain
      schema:
        type: string  

    

  schemas:

    Error:
      type: object
      description: Chybové hlášení
      properties:
        status:
          type: string
        statusCase:
          type: string
        msg:
          type: string
      required:
        - status
        - statusCase
        - msg

    LoginRequest:
      type: object
      description: Authentication request
      properties:
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password
      
    LoginResponse:
      type: object
      description: Authentication response
      properties:
        name:
          type: string
        id:
          type: string
        email:
          type: string
        role:
          type: array
          items:
            type: string
        token:
          type: string
        status:
          type: string
        statusCase:
          type: string
        msg:
          type: string
          
      required:
        - name
        - id
        - email
        - role
        - token
        - status
        - statusCase
        - msg

    GenericRequest:
      type: object
      description: Authentication request
      

    GenericResponse:
      type: object
      description: Authentication request
      

    TokenRequest:
      type: object
      description: JWT token test request for security admin/participant and for admin/business app (notarius) scenarios. No dummy jwt tokens are accepted
      properties:
        user_id:
          type: string
        company_id:
          type: string
        iss:
          type: string
        
      required:
        - user_id
        - company_id
        - iss
    
    TokenResponse:
      type: object
      description: JWT token test response for use in other API calls
      properties:
        token:
          type: string

    

      



 